// Maps raw activity log action keys to human-friendly labels.
export const ACTIVITY_LABELS: Record<string, string> = {
  login: "User Logged In",
  logout: "User Logged Out",
  signup: "User Signed Up",
  "course.created": "Course Created",
  "course.updated": "Course Updated",
  "course.approved": "Course Approved",
  "course.rejected": "Course Rejected",
  "course.deleted": "Course Deleted",
  "course.archived": "Course Archived",
  "course.restored": "Course Restored",
  "course.submitted": "Course Submitted",
  "assignment.created": "Assignment Created",
  "assignment.graded": "Assignment Graded",
  "assignment.submitted": "Assignment Submitted",
  "assignment.deleted": "Assignment Deleted",
  "enrollment.created": "Student Enrolled",
  "lesson.completed": "Lesson Completed",
  "profile.updated": "Profile Updated",
  "role.changed": "Role Changed",
  "coupon.created": "Coupon Created",
  "coupon.deleted": "Coupon Deleted",
  "coupon.toggled": "Coupon Toggled",
  "job.created": "Job Posted",
  "job.updated": "Job Updated",
  "job.deleted": "Job Deleted",
  "job.toggled": "Job Toggled",
  "event.created": "Event Created",
  "event.updated": "Event Updated",
  "event.deleted": "Event Deleted",
  "event.approved": "Event Approved",
  "event.rejected": "Event Rejected",
  "category.created": "Program Created",
  "category.updated": "Program Updated",
  "category.deleted": "Program Deleted",
  "volunteer.submitted": "Volunteer Application",
  "volunteer.status_updated": "Volunteer Status Updated",
  "inquiry.submitted": "Inquiry Received",
  "inquiry.status_updated": "Inquiry Status Updated",
  "inquiry.deleted": "Inquiry Deleted",
  "students.exported": "Students Exported",
  "curriculum.section_added": "Curriculum Section Added",
  "curriculum.section_deleted": "Curriculum Section Deleted",
  "schedule.created": "Schedule Created",
  "schedule.updated": "Schedule Updated",
  "schedule.deleted": "Schedule Deleted",
  "class_log.created": "Class Logged",
  "class_log.confirmed": "Class Confirmed",
  "project.created": "Project Created",
  "project.deleted": "Project Deleted",
  "certificate.uploaded": "Certificate Uploaded",
  "allocation.created": "Subject Allocated",
  "allocation.deleted": "Allocation Removed",
  "feedback.replied": "Feedback Replied",
};

export const labelForAction = (action: string) => ACTIVITY_LABELS[action] || action;
